
CREATE TABLE "USUARIOS" (
    ID INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(256) NOT NULL,
    USERNAME VARCHAR(50),
    EMAIL VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(70) NOT NULL,
    TELEFONO VARCHAR(11),
    TIPO VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL
);


CREATE TABLE "PRODUCTOS" (
    ID INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(256) NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    IMAGEN VARCHAR(100),
    PRECIO DOUBLE NOT NULL,
    CANTIDAD INT NOT NULL
);


CREATE TABLE "ORDENES"(
	ID INTEGER IDENTITY PRIMARY KEY,
    NUMERO VARCHAR(256) NOT NULL,
    FECHACREACION DATE NOT NULL,
    FECHARECIBIDA DATE,
    TOTAL DOUBLE NOT NULL
);




CREATE TABLE "DETALLES" (
    ID INTEGER IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR(256) NOT NULL,
    CANTIDAD DOUBLE NOT NULL,
    PRECIO DOUBLE NOT NULL,
    TOTAL DOUBLE NOT NULL
);